version: "2"

networks:
  test:

services:
  # ca-seedsAssociation:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca.seedsAssociation.example.com
  #     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seedsAssociation.example.com-cert.pem
  #     - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.seedsAssociation.example.com-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
  #   ports:
  #     - "7054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/seedsAssociation.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
  #     - ./crypto-config/peerOrganizations/seedsAssociation.example.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
  #   container_name: ca.seedsAssociation.example.com
  #   hostname: ca.seedsAssociation.example.com
  #   networks:
  #     - test


  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - test

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - test

  peer0.seedsAssociation.example.com:
    container_name: peer0.seedsAssociation.example.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=SeedsAssociationMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=peer0.seedsAssociation.example.com
      - CORE_PEER_ADDRESS=peer0.seedsAssociation.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.seedsAssociation.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.seedsAssociation.example.com:8051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seedsAssociation.example.com:7051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb0
    ports:
      - 7051:7051
    volumes:
      - ./crypto-config/peerOrganizations/seedsAssociation.example.com/peers/peer0.seedsAssociation.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/seedsAssociation.example.com/peers/peer0.seedsAssociation.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test

  peer1.seedsAssociation.example.com:
    container_name: peer1.seedsAssociation.example.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=SeedsAssociationMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=peer1.seedsAssociation.example.com
      - CORE_PEER_ADDRESS=peer1.seedsAssociation.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.seedsAssociation.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.seedsAssociation.example.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seedsAssociation.example.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 8051:8051
    volumes:
      - ./crypto-config/peerOrganizations/seedsAssociation.example.com/peers/peer1.seedsAssociation.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/seedsAssociation.example.com/peers/peer1.seedsAssociation.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.seedsAssociation.example.com:7051
      - CORE_PEER_LOCALMSPID=SeedsAssociationMSP
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/SeedsAssociationMSP

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/seedsAssociation.example.com/peers/peer0.seedsAssociation.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/seedsAssociation.example.com/peers/peer0.seedsAssociation.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/seedsAssociation.example.com/peers/peer0.seedsAssociation.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/peerOrganizations/seedsAssociation.example.com/users/Admin@seedsAssociation.example.com/msp

      - CORE_CHAINCODE_KEEPALIVE=10 
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    networks:
      - test
    volumes:
      - /var/run/:/host/var/run/
      # - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./crypto-config/peerOrganizations/seedsAssociation.example.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/seedsAssociation.example.com/
      - ./../vm2/crypto-config/peerOrganizations/farmersAssociation.example.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/farmersAssociation.example.com/
      - ./../vm3/crypto-config/peerOrganizations/merchantsAssociation.example.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/merchantsAssociation.example.com/
      - ./../vm4/crypto-config/ordererOrganizations/example.com/:/etc/hyperledger/channel/crypto-config/ordererOrganizations/example.com/
